name: CI
on:
  pull_request: ~

env:
  DEVBOX_VERSION: 0.17.2

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Restore go vendors
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-deps-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-deps-${{ runner.os }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: "true"
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Run golangci-lint
        run: make lint
