name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 #v4.2.1
        with:
          go-version: 1.19
          cache: false

      - run: make install

      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: goreleaser release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dist
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 #v3.2.1
        with:
          name: dist
          path: dist
